//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeWork2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomeWork2.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by student Vasyl Kusmii.
        /// </summary>
        public static string Footer_Text {
            get {
                return ResourceManager.GetString("Footer.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animals.
        /// </summary>
        public static string Head_Title {
            get {
                return ResourceManager.GetString("Head.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add animal.
        /// </summary>
        public static string Nav_AddAnimal {
            get {
                return ResourceManager.GetString("Nav.AddAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animals.
        /// </summary>
        public static string Nav_Animals {
            get {
                return ResourceManager.GetString("Nav.Animals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Nav_Home {
            get {
                return ResourceManager.GetString("Nav.Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string PageAddAnimal_BtnAdd {
            get {
                return ResourceManager.GetString("PageAddAnimal.BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field of animal name is reqiured.
        /// </summary>
        public static string PageAddAnimal_Form_ErrorMessageName {
            get {
                return ResourceManager.GetString("PageAddAnimal.Form.ErrorMessageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field of animal sound is reqiured.
        /// </summary>
        public static string PageAddAnimal_Form_ErrorMessageSound {
            get {
                return ResourceManager.GetString("PageAddAnimal.Form.ErrorMessageSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add animal.
        /// </summary>
        public static string PageAddAnimal_NameForm {
            get {
                return ResourceManager.GetString("PageAddAnimal.NameForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PageAddAnimal_PlaceholderName {
            get {
                return ResourceManager.GetString("PageAddAnimal.PlaceholderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        public static string PageAddAnimal_PlaceholderSound {
            get {
                return ResourceManager.GetString("PageAddAnimal.PlaceholderSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add animal.
        /// </summary>
        public static string PageAnimalDetails_BtnAddAnimal {
            get {
                return ResourceManager.GetString("PageAnimalDetails.BtnAddAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To all animals.
        /// </summary>
        public static string PageAnimalDetails_BtnToAllAnimals {
            get {
                return ResourceManager.GetString("PageAnimalDetails.BtnToAllAnimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string PageAnimals_RefInfo {
            get {
                return ResourceManager.GetString("PageAnimals.RefInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animals.
        /// </summary>
        public static string PageAnimals_TextHead {
            get {
                return ResourceManager.GetString("PageAnimals.TextHead", resourceCulture);
            }
        }
    }
}
